### ISSUE TITLE
是否可以添加 padding 和 圆角 的参数设置

### ISSUE THREAD

**Issue by zhaokuohaha** [mo-jinran/VisualRecord#1]
如题， 如果可以添加上下边距和圆角的设置，感觉看起来效果会更好

**Comment by mo-jinran** [comment]
不可以，这不属于这个插件的职责，不包括列表美化，不会做与核心功能无关的，请使用其他主题插件美化

**Comment by zhaokuohaha** [comment]
> @mo-jinran  不可以，这不属于这个插件的职责，不包括列表美化，不会做与核心功能无关的，请使用其他主题插件美化

额，我的理解，这个和现在已经实现的背景色一样， 是属于插件的一部分， 应该不需要其他主题插件的。 另外其他主题插件安装的时候也不保证已经装了本插件，所以放在其他主题插件也不是很合理。

**Comment by mo-jinran** [comment]
这本身就是个独立插件，样式遵守原版网易云音乐。爱用不用，你的态度是问问题的，而不是来当大爷的
